# -*- coding: utf-8 -*-
"""Akbank Bootcamp Proje.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MHAotcFXMOYWXr9w6Jn1_xP5d_AhDAeB
"""

#Library Management System

class Library:
    def __init__(self):
        self.file = open("books.txt", "a+")

    def __del__(self):
        self.file.close()

    def list_books(self):
        self.file.seek(0)  # Dosyanın başına git
        books = self.file.readlines()
        if books:
            for book in books:
                book_info = book.strip().split(',')
                print("Book Name: {}, Author: {}".format(book_info[0], book_info[1]))
        else:
            print("The library is empty.")

    def add_book(self):
        title = input("Book Name: ")
        author = input("Author: ")
        release_year = input("Publication Year: ")
        page_count = input("Number of pages: ")
        book_info = f"{title},{author},{release_year},{page_count}\n"
        self.file.write(book_info)
        print("The book has been added successfully.")

    def remove_book(self):
        title_to_remove = input("Book Name to be Removed: ")
        self.file.seek(0)
        books = self.file.readlines()
        new_books = []
        found = False
        for book in books:
            if title_to_remove not in book:
                new_books.append(book)
            else:
                found = True
        if found:
            self.file.seek(0)
            self.file.truncate()
            self.file.writelines(new_books)
            print(f"The book titled '{title_to_remove}' has been removed.")
        else:
            print(f"The book titled '{title_to_remove}' could not be found.")


lib = Library()

while True:
    print("*** MENU***")
    print("1) List Books")
    print("2) Add Book")
    print("3) Remove Book")
    print("Q) Quit")
    choice = input("Enter your choice: ")

    if choice == '1':
        lib.list_books()
    elif choice == '2':
        lib.add_book()
    elif choice == '3':
        lib.remove_book()
    elif choice.lower() == 'q':
        break
    else:
        print("Invalid login. Please try again.")